update AppOpsService.Java and UiModeManagerServiceJava
Fix more build errors: frameworks/base/services/core/java/com/android/server/appop/AppOpsService.java:1831: error: method checkOperationUnch
ecked in class AppOpsService cannot be applied to given types;
        return checkOperationUnchecked(code, uid, resolvedPackageName, raw);
               ^
  required: int,int,String,boolean,boolean
  found: int,int,String,boolean
  reason: actual and formal argument lists differ in length
frameworks/base/services/core/java/com/android/server/appop/AppOpsService.java:1850: error: cannot find symbol
            if (isOpRestrictedLocked(uid, code, packageName, isPrivileged)) {
                                                             ^
  symbol:   variable isPrivileged
  location: class AppOpsService
frameworks/base/services/core/java/com/android/server/appop/AppOpsService.java:2051: error: method isOpRestrictedLock
ed in class AppOpsService cannot be applied to given types;
            if (isOpRestrictedLocked(uid, code, packageName, isPrivileged)) {
                ^
  required: int,int,String
  found: int,int,String,boolean
  reason: actual and formal argument lists differ in length
frameworks/base/services/core/java/com/android/server/appop/AppOpsService.java:2228: error: method isOpRestrictedLock
ed in class AppOpsService cannot be applied to given types;
            if (isOpRestrictedLocked(uid, code, resolvedPackageName, isPrivileged)) {
                ^
  required: int,int,String
  found: int,int,String,boolean
  reason: actual and formal argument lists differ in length
frameworks/base/services/core/java/com/android/server/appop/AppOpsService.java:2777: error: cannot find symbol
                        Ops ops = getOpsRawLocked(uid, packageName, isPrivileged,
                                                                    ^
  symbol:   variable isPrivileged
  location: class AppOpsService
frameworks/base/services/core/java/com/android/server/UiModeManagerService.java:526: error: cannot find symbol
                            if (UserManager.get(getContext()).isPrimaryUser()) {
                                ^
  symbol: variable UserManager