Update NotificationPanelView.java
fix more build errors: error: /media/wavedashdoc/Storage/android/pixeldust10/frameworks/base/packages/SystemUI/src/com/android/systemui/stat
usbar/phone/NotificationPanelView.java:387: error: cannot find symbol
    private SettingsObserver mSettingsObserver;
            ^
  symbol:   class SettingsObserver
  location: class NotificationPanelView
error: /media/wavedashdoc/Storage/android/pixeldust10/frameworks/base/packages/SystemUI/src/com/android/systemui/stat
usbar/phone/NotificationPanelView.java:388: error: cannot find symbol
    private Handler mHandler = new Handler();
            ^
  symbol:   class Handler
  location: class NotificationPanelView
error: /media/wavedashdoc/Storage/android/pixeldust10/frameworks/base/packages/SystemUI/src/com/android/systemui/clas
sifier/brightline/BrightLineFalsingManager.java:58: error: cannot find symbol
    private final ExecutorService mBackgroundExecutor = Executors.newSingleThreadExecutor();
                  ^
  symbol:   class ExecutorService
  location: class BrightLineFalsingManager
error: /media/wavedashdoc/Storage/android/pixeldust10/frameworks/base/packages/SystemUI/src/com/android/systemui/stat
usbar/phone/NotificationPanelView.java:128: error: [ComponentProcessor:MiscError] dagger.internal.codegen.ComponentPr
ocessor was unable to process this class because not all of its dependencies could be resolved. Check for compilation
 errors or a circular dependency with generated code.