update AppOpsService.java
Fix more build errors: frameworks/base/services/core/java/com/android/server/appop/AppOpsService.java:1858: error: cannot find symbol
            if (isOpRestrictedLocked(uid, code, packageName, isPrivileged)) {
                                                             ^
  symbol:   variable isPrivileged
  location: class AppOpsService
frameworks/base/services/core/java/com/android/server/appop/AppOpsService.java:2051: error: cannot find symbol
            if (isOpRestrictedLocked(uid, code, packageName, isPrivileged)) {
                                                             ^
  symbol:   variable isPrivileged
  location: class AppOpsService
frameworks/base/services/core/java/com/android/server/appop/AppOpsService.java:2228: error: method isOpRestrictedLock
ed in class AppOpsService cannot be applied to given types;
            if (isOpRestrictedLocked(uid, code, resolvedPackageName, isPrivileged)) {
                ^
  required: int,int,String
  found: int,int,String,boolean
  reason: actual and formal argument lists differ in length